"""Record mode: onboard a new brand in minutes instead of writing code.

An engineer clicks through the target router once.  While they do, we:
  * capture every network request/response to a HAR file (the "reverse the HTTP
    API" fallback asset -- free of charge), and
  * drop a profile *draft* skeleton they can fill in with the few selectors the
    heuristics missed.

For rich selector recording you can also run Playwright's built-in codegen:
    python -m playwright codegen http://192.168.1.1
This module focuses on the offline-capturable parts (HAR + draft).
"""
from __future__ import annotations

import os
from typing import Optional

from playwright.sync_api import sync_playwright

from config import Config, DEFAULT

DRAFT_TEMPLATE = """\
# Profile draft generated by recorder.py -- fill in only what heuristics missed.
# Every key is OPTIONAL; delete the ones you don't need.
brand: "{brand}"
model: "{model}"
firmware: ""

# Ordered menu labels to reach WAN settings (only if heuristic nav fails):
# wan_path: ["Advanced", "Network", "WAN"]

# CSS/text selector overrides, keyed by concept:
# selectors:
#   dial_mode_select: "#wanType"
#   login_pass: "#password"
#   pppoe_user: "#pppoeAcc"

# Exact option label this model uses for a canonical mode (if odd wording):
# mode_labels:
#   pppoe: "PPPoE(ADSL虚拟拨号)"
"""


def record(url: str, brand: str = "unknown", model: str = "model",
           out_dir: str = "recordings", config: Optional[Config] = None) -> dict:
    cfg = config or DEFAULT
    cfg.apply_env()
    os.makedirs(out_dir, exist_ok=True)
    safe = "%s_%s" % (brand or "unknown", model or "model")
    har_path = os.path.join(out_dir, safe + ".har")
    draft_path = os.path.join(PROFILE_DIR(), safe + ".yaml")

    print("[record] Opening %s -- click through the dial-mode change, then "
          "close the browser window to finish." % url)

    with sync_playwright() as pw:
        browser = _launch(pw, cfg)
        context = browser.new_context(ignore_https_errors=True,
                                      record_har_path=har_path)
        page = context.new_page()
        try:
            page.goto(url, wait_until="domcontentloaded")
        except Exception as exc:
            print("[record] initial navigation warning: %s" % exc)
        # Block until the engineer closes the page/window.
        try:
            page.wait_for_event("close", timeout=0)
        except Exception:
            pass
        context.close()  # flushes the HAR
        browser.close()

    if not os.path.exists(draft_path):
        with open(draft_path, "w", encoding="utf-8") as fh:
            fh.write(DRAFT_TEMPLATE.format(brand=brand, model=model))
        made_draft = True
    else:
        made_draft = False

    print("[record] HAR saved -> %s" % har_path)
    print("[record] profile draft %s -> %s"
          % ("created" if made_draft else "already existed", draft_path))
    return {"har": har_path, "draft": draft_path, "draft_created": made_draft}


def _launch(pw, cfg: Config):
    kwargs = {"headless": False}  # recording is always interactive
    if cfg.executable_path:
        return pw.chromium.launch(executable_path=cfg.executable_path, **kwargs)
    if cfg.channel:
        try:
            return pw.chromium.launch(channel=cfg.channel, **kwargs)
        except Exception:
            pass
    return pw.chromium.launch(**kwargs)


def PROFILE_DIR() -> str:
    d = os.path.join(os.path.dirname(os.path.dirname(__file__)), "profiles")
    os.makedirs(d, exist_ok=True)
    return d
